# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Cebuano spellchecker"
ceb = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Cebuano, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ceb = "TRANSLATE: A spellchecker for Cebuano, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ceb"

[windows]
system_product_code = "{REPLACE_WITH_REAL_SYSTEM_PROD_CODE}_is1"

[package.speller]
name = "Cebuano"
version = "0.1.0"

[package.grammar]
name = "Cebuano"
version = "0.1.0"

[package.tts-text-proc]
name = "Cebuano"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
