template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "cebu1242"
__REPO__ = "lang-ceb"
__UND2C__ = "ceb"
__UNDEFINED__ = "Cebuano"
__UND__ = "ceb"
___LICENSE__ = "LGPLv3"
